In [1]:

import pandas as pd

# Load the CSV file containing target variables
csv_file_path = "D:/GTDPP/merged_data.csv"  # Path to your dataset
data = pd.read_csv(csv_file_path)

# Display the first few rows to understand the structure of the data
data.head()

,Image ID,Image_ID,Image Name,Product Name,Garment Category,Material Composition,Material Description,Textural Features,Sustainability Features,Color,...,Features,Product_Type,Carbon_Emission_from_RM(KG CO2),Carbon_Emission_from_WDFKG CO2),Energy_Consumption_from_WDF(KwH),Water_Used_from_WDF (Litres),Carbon_Emission_from_MKG CO2),Energy_Consumption_from_M(KwH),Water_Used_from_M (Litres),Carbon_Emission_from T(KG CO2)
0,Fashion_1.jpg,Fashion_7.jpg,Image 7: Olive Green Performance T-Shirt with ...,Olive Green Performance Tee,Active Fashion,100% Polyester,"Synthetic, lightweight, moisture-wicking","Smooth, slightly stretchy, mesh-like texture",Moisture-wicking fabric,Olive green with subtle print,...,[ 2.44760156e+00 1.29343867e-01 -1.38904715e+...,Fashion,8.07713,1.642961,20,488,6.548923,68,415,1.410117
1,Fashion_10.jpg,Fashion_7.jpg,Image 7: Olive Green Performance T-Shirt with ...,Olive Green Performance Tee,Active Fashion,100% Polyester,"Synthetic, lightweight, moisture-wicking","Smooth, slightly stretchy, mesh-like texture",Moisture-wicking fabric,Olive green with subtle print,...,[ 2.44760156e+00 1.29343867e-01 -1.38904715e+...,Fashion,8.07713,1.642961,20,488,6.548923,68,415,1.410117
2,Fashion_11.jpg,Fashion_7.jpg,Image 7: Olive Green Performance T-Shirt with ...,Olive Green Performance Tee,Active Fashion,100% Polyester,"Synthetic, lightweight, moisture-wicking","Smooth, slightly stretchy, mesh-like texture",Moisture-wicking fabric,Olive green with subtle print,...,[ 2.44760156e+00 1.29343867e-01 -1.38904715e+...,Fashion,8.07713,1.642961,20,488,6.548923,68,415,1.410117
3,Fashion_12.jpg,Fashion_7.jpg,Image 7: Olive Green Performance T-Shirt with ...,Olive Green Performance Tee,Active Fashion,100% Polyester,"Synthetic, lightweight, moisture-wicking","Smooth, slightly stretchy, mesh-like texture",Moisture-wicking fabric,Olive green with subtle print,...,[ 2.44760156e+00 1.29343867e-01 -1.38904715e+...,Fashion,8.07713,1.642961,20,488,6.548923,68,415,1.410117
4,Fashion_45.jpg,Fashion_7.jpg,Image 7: Olive Green Performance T-Shirt with ...,Olive Green Performance Tee,Active Fashion,100% Polyester,"Synthetic, lightweight, moisture-wicking","Smooth, slightly stretchy, mesh-like texture",Moisture-wicking fabric,Olive green with subtle print,...,[ 2.44760156e+00 1.29343867e-01 -1.38904715e+...,Fashion,8.07713,1.642961,20,488,6.548923,68,415,1.410117

In [2]:
# Print all column names and their data types
print(data.dtypes)

Image ID                             object
Image_ID                             object
Image Name                           object
Product Name                         object
Garment Category                     object
Material Composition                 object
Material Description                 object
Textural Features                    object
Sustainability Features              object
Color                                object
Manufacturing Complexity             object
Design Features                      object
Dyeing Process                       object
Weight of Garment                    object
Packaging Type                       object
Material Type                        object
Garment Type                         object
Product Design                       object
Headline/Screen Text                 object
Production Process Indicators        object
Features                             object
Product_Type                         object
Carbon_Emission_from_RM(KG CO2)     float64
Carbon_Emission_from_WDFKG CO2)     float64
Energy_Consumption_from_WDF(KwH)      int64
Water_Used_from_WDF (Litres)          int64
Carbon_Emission_from_MKG CO2)       float64
Energy_Consumption_from_M(KwH)        int64
Water_Used_from_M (Litres)            int64
Carbon_Emission_from T(KG CO2)      float64
dtype: object

In [3]:
# Check for missing values in the dataset
data.isnull().sum()

Image ID                            0
Image_ID                            0
Image Name                          0
Product Name                        0
Garment Category                    0
Material Composition                0
Material Description                0
Textural Features                   0
Sustainability Features             0
Color                               0
Manufacturing Complexity            0
Design Features                     0
Dyeing Process                      0
Weight of Garment                   0
Packaging Type                      0
Material Type                       0
Garment Type                        0
Product Design                      0
Headline/Screen Text                0
Production Process Indicators       0
Features                            0
Product_Type                        0
Carbon_Emission_from_RM(KG CO2)     0
Carbon_Emission_from_WDFKG CO2)     0
Energy_Consumption_from_WDF(KwH)    0
Water_Used_from_WDF (Litres)        0
Carbon_Emission_from_MKG CO2)       0
Energy_Consumption_from_M(KwH)      0
Water_Used_from_M (Litres)          0
Carbon_Emission_from T(KG CO2)      0
dtype: int64

In [4]:
numerical_features = data.select_dtypes(include=['float64', 'int64']).columns
print("Numerical Features:")
print(numerical_features)

Numerical Features:
Index(['Carbon_Emission_from_RM(KG CO2)', 'Carbon_Emission_from_WDFKG CO2)',
       'Energy_Consumption_from_WDF(KwH)', 'Water_Used_from_WDF (Litres)',
       'Carbon_Emission_from_MKG CO2)', 'Energy_Consumption_from_M(KwH)',
       'Water_Used_from_M (Litres)', 'Carbon_Emission_from T(KG CO2)'],
      dtype='object')

In [5]:
categorical_features = data.select_dtypes(include=['object']).columns
print("Categorical and Text Features:")
print(categorical_features)

Categorical and Text Features:
Index(['Image ID', 'Image_ID', 'Image Name', 'Product Name',
       'Garment Category', 'Material Composition', 'Material Description',
       'Textural Features', 'Sustainability Features', 'Color',
       'Manufacturing Complexity', 'Design Features', 'Dyeing Process',
       'Weight of Garment', 'Packaging Type', 'Material Type', 'Garment Type',
       'Product Design', 'Headline/Screen Text',
       'Production Process Indicators', 'Features', 'Product_Type'],
      dtype='object')

In [6]:
from sklearn.preprocessing import StandardScaler

numerical_columns = ['Carbon_Emission_from_RM(KG CO2)', 'Carbon_Emission_from_WDFKG CO2)',
       'Energy_Consumption_from_WDF(KwH)', 'Water_Used_from_WDF (Litres)',
       'Carbon_Emission_from_MKG CO2)', 'Energy_Consumption_from_M(KwH)',
       'Water_Used_from_M (Litres)', 'Carbon_Emission_from T(KG CO2)']
scaler = StandardScaler()
data[numerical_columns] = scaler.fit_transform(data[numerical_columns])

In [7]:
# Drop duplicates
data.drop_duplicates(inplace=True)

In [8]:
from sklearn.preprocessing import LabelEncoder

# Ensure LabelEncoder is defined
le = LabelEncoder()

# Encode the specified categorical columns
categorical_columns_to_encode = ['Product_Type', 'Garment Category', 'Material Type']
for column in categorical_columns_to_encode:
    data[column] = le.fit_transform(data[column])

In [9]:
# import re
# from nltk.corpus import stopwords
# nltk.download('stopwords')

# def clean_text(text):
#     text = text.lower()  # Lowercase the text
#     text = re.sub(r'[^a-z\s]', '', text)  # Remove punctuation and numbers
#     text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])  # Remove stopwords
#     return text

# merged_data['cleaned_text'] = merged_data['Product_Name'].apply(clean_text)  # Or any other textual feature

In [10]:
# Extract all textual features from the dataset
textual_features = ['Product Name', 'Material Composition', 'Material Description', 
                    'Textural Features', 'Sustainability Features', 'Color', 
                    'Design Features', 'Dyeing Process', 'Packaging Type', 
                    'Garment Type', 'Product Design', 'Headline/Screen Text', 
                    'Production Process Indicators', 'Features']

# Display the textual features
for feature in textual_features:
    print(f"{feature}:\n", data[feature].head(), "\n")

Product Name:
 0    Olive Green Performance Tee
1    Olive Green Performance Tee
2    Olive Green Performance Tee
3    Olive Green Performance Tee
4    Olive Green Performance Tee
Name: Product Name, dtype: object

Material Composition:
 0    100% Polyester
1    100% Polyester
2    100% Polyester
3    100% Polyester
4    100% Polyester
Name: Material Composition, dtype: object

Material Description:
 0    Synthetic, lightweight, moisture-wicking
1    Synthetic, lightweight, moisture-wicking
2    Synthetic, lightweight, moisture-wicking
3    Synthetic, lightweight, moisture-wicking
4    Synthetic, lightweight, moisture-wicking
Name: Material Description, dtype: object

Textural Features:
 0    Smooth, slightly stretchy, mesh-like texture
1    Smooth, slightly stretchy, mesh-like texture
2    Smooth, slightly stretchy, mesh-like texture
3    Smooth, slightly stretchy, mesh-like texture
4    Smooth, slightly stretchy, mesh-like texture
Name: Textural Features, dtype: object

Sustainability Features:
 0    Moisture-wicking fabric
1    Moisture-wicking fabric
2    Moisture-wicking fabric
3    Moisture-wicking fabric
4    Moisture-wicking fabric
Name: Sustainability Features, dtype: object

Color:
 0    Olive green with subtle print
1    Olive green with subtle print
2    Olive green with subtle print
3    Olive green with subtle print
4    Olive green with subtle print
Name: Color, dtype: object

Design Features:
 0    Crew neck, short sleeves, subtle leaf print
1    Crew neck, short sleeves, subtle leaf print
2    Crew neck, short sleeves, subtle leaf print
3    Crew neck, short sleeves, subtle leaf print
4    Crew neck, short sleeves, subtle leaf print
Name: Design Features, dtype: object

Dyeing Process:
 0    Sublimation printing
1    Sublimation printing
2    Sublimation printing
3    Sublimation printing
4    Sublimation printing
Name: Dyeing Process, dtype: object

Packaging Type:
 0    Folded with tag in a plastic sleeve
1    Folded with tag in a plastic sleeve
2    Folded with tag in a plastic sleeve
3    Folded with tag in a plastic sleeve
4    Folded with tag in a plastic sleeve
Name: Packaging Type, dtype: object

Garment Type:
 0    Performance T-shirt
1    Performance T-shirt
2    Performance T-shirt
3    Performance T-shirt
4    Performance T-shirt
Name: Garment Type, dtype: object

Product Design:
 0    Short sleeve top, athletic style
1    Short sleeve top, athletic style
2    Short sleeve top, athletic style
3    Short sleeve top, athletic style
4    Short sleeve top, athletic style
Name: Product Design, dtype: object

Headline/Screen Text:
 0    Move Freely
1    Move Freely
2    Move Freely
3    Move Freely
4    Move Freely
Name: Headline/Screen Text, dtype: object

Production Process Indicators:
 0    Sublimation printing, moisture-wicking finish
1    Sublimation printing, moisture-wicking finish
2    Sublimation printing, moisture-wicking finish
3    Sublimation printing, moisture-wicking finish
4    Sublimation printing, moisture-wicking finish
Name: Production Process Indicators, dtype: object

Features:
 0    [ 2.44760156e+00  1.29343867e-01 -1.38904715e+...
1    [ 2.44760156e+00  1.29343867e-01 -1.38904715e+...
2    [ 2.44760156e+00  1.29343867e-01 -1.38904715e+...
3    [ 2.44760156e+00  1.29343867e-01 -1.38904715e+...
4    [ 2.44760156e+00  1.29343867e-01 -1.38904715e+...
Name: Features, dtype: object

In [11]:
import re
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

# Define the text cleaning function
def clean_text(text):
    text = text.lower()  # Lowercase the text
    text = re.sub(r'[^a-z\s]', '', text)  # Remove punctuation and numbers
    text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])  # Remove stopwords
    return text

# List of all feature columns to clean
text_columns = ['Product Name', 'Material Composition', 'Material Description', 
                'Textural Features', 'Sustainability Features', 'Color', 
                'Design Features', 'Dyeing Process', 'Packaging Type', 
                'Garment Type', 'Product Design', 'Headline/Screen Text', 
                'Production Process Indicators', 'Features']

# Apply the clean_text function to each of these columns
for col in text_columns:
    data[f'cleaned_{col}'] = data[col].apply(clean_text)

# Display the cleaned data to confirm
data[['Product Name', 'cleaned_Product Name', 'Material Composition', 'cleaned_Material Composition']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Product Name,cleaned_Product Name,Material Composition,cleaned_Material Composition
0,Olive Green Performance Tee,olive green performance tee,100% Polyester,polyester
1,Olive Green Performance Tee,olive green performance tee,100% Polyester,polyester
2,Olive Green Performance Tee,olive green performance tee,100% Polyester,polyester
3,Olive Green Performance Tee,olive green performance tee,100% Polyester,polyester
4,Olive Green Performance Tee,olive green performance tee,100% Polyester,polyester

In [12]:
from transformers import BertTokenizer

# Load the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Combine relevant cleaned columns into a single 'cleaned_text' column if needed
data['cleaned_text'] = data['cleaned_Product Name'] + " " + data['cleaned_Material Composition'] + " " + data['cleaned_Material Description']

# Tokenize the text
data['tokenized_text'] = data['cleaned_text'].apply(lambda x: tokenizer.encode(x, add_special_tokens=True))

In [13]:
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

def clean_text(text):
    text = text.lower()  # Lowercase the text
    text = re.sub(r'[^a-z\s]', '', text)  # Remove punctuation and numbers
    text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])  # Remove stopwords
    return text

 
            
data['cleaned_text'] = data['Product Name'] + " " + data['Material Composition'] + " " + data['Material Description'] + " " + data['Textural Features'] + " " + data['Sustainability Features'] + " " + data['Color'] + " " + data['Design Features'] +" " + data['Dyeing Process'] + " " + data['Packaging Type'] + " " + data['Garment Type'] + " " + data['Product Design'] + " " + data['Headline/Screen Text'] + " " + data['Production Process Indicators'] + " " + data['Features']
data['tokenized_text'] = data['cleaned_text'].apply(lambda x: tokenizer.encode(x, add_special_tokens=True)) # Or any other textual feature

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Token indices sequence length is longer than the specified maximum sequence length for this model (10310 > 512). Running this sequence through the model will result in indexing errors

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = 128  # Set the max sequence length

# Pad the tokenized sequences
padded_sequences = pad_sequences(data['tokenized_text'], maxlen=max_length, padding='post', truncating='post')

# Convert the padded sequences to a list and assign to the DataFrame
data['padded_text'] = padded_sequences.tolist()

In [15]:
import numpy as np

# Example: concatenating numerical and categorical features with the text embeddings
X_text = np.array(data['padded_text'].tolist())  # Text input (tokenized and padded)
X_numeric = data.drop(columns=['Carbon_Emission_from_RM(KG CO2)', 'Carbon_Emission_from_WDFKG CO2)', 'Energy_Consumption_from_WDF(KwH)', 'Water_Used_from_WDF (Litres)', 'Carbon_Emission_from_MKG CO2)', 'Energy_Consumption_from_M(KwH)', 'Water_Used_from_M (Litres)', 'Carbon_Emission_from T(KG CO2)', 'Product_Type', 'Garment Category', 'Material Type' , 'cleaned_text', 'tokenized_text', 'padded_text'])  # Numeric and categorical features